name: Auto-Fill PR Description

on:
  pull_request:
    types: [opened, reopened]

jobs:
  fill-pr-description:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Install dependencies
        run: |
          dotnet tool install -g Microsoft.dotnet-interactive
          dotnet interactive jupyter install
      
      - name: Create .env file
        run: |
          cat << EOF > .env
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          GITHUB_OWNER=${{ github.repository_owner }}
          GITHUB_REPO=${{ github.event.repository.name }}
          PR_NUMBER=${{ github.event.pull_request.number }}
          EOF
      
      - name: Run PR Description Agent
        run: |
          dotnet script run-pr-agent.csx
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
      
      - name: Update PR Description
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const description = fs.readFileSync('pr-description-output.md', 'utf8');
            
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              body: description
            });
            
            console.log('✅ PR description updated successfully!');
